# -*- coding: utf-8 -*-
"""CNN-YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlsvAcwRQTUcTiI19qSwBOCktrpWNrYg
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x
import tensorflow 
from imageai.Detection.Custom import CustomObjectDetection, CustomVideoObjectDetection
from imageai.Detection import ObjectDetection,VideoObjectDetection
import os

# execution_path = os.getcwd()
#@markdown Mention the path of the directory.
#@markdown  Make sure yolo.h5 is available in this directory. 
execution_path = os.getcwd() #@param {type:'string'}


def imageDetection():
  detector = ObjectDetection()
  detector.setModelTypeAsYOLOv3()
  detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
  detector.loadModel()
  # detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "traffic-light.jpg"), output_image_path=os.path.join(execution_path , "image2new.jpg"), minimum_percentage_probability=30)
  custom_objects = detector.CustomObjects(car=True, motorcycle=True,bus=True,  truck=True,person=True,  bicycle=True)
  detections = detector.detectCustomObjectsFromImage(custom_objects=custom_objects, input_image=os.path.join(execution_path , "traffic-light.jpg"), output_image_path=os.path.join(execution_path , "image3custom.jpg"), minimum_percentage_probability=30)
  for eachObject in detections:
      print(eachObject["name"] , " : ", eachObject["percentage_probability"], " : ", eachObject["box_points"] )
      print("--------------------------------")

def videoDection():
  detector = VideoObjectDetection()
  detector.setModelTypeAsYOLOv3()
  detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
  detector.loadModel()

  video_path = detector.detectObjectsFromVideo(input_file_path=os.path.join(execution_path, "Traffic-20581.mp4"),
                                  output_file_path=os.path.join(execution_path, "traffic_detected")
                                  , frames_per_second=20, log_progress=True)
  print(video_path)


#@markdown Detect objects on an image.
isImage = True #@param {type:"boolean"}
#@markdown Mention the path of image.
image_path = execution_path + '/content/traffic.jpg' #@param {type:"string"}
#@markdown Detect objects on a video.

isVideo = True #@param {type:"boolean"}
#@markdown Mention the path of video.
video_path = execution_path+ '/content/traffic.mp4' #@param {type:"string"}
#@markdown Now run this Cell


if isImage and isVideo:
  print("Detecting the objects in the given image")
  imageDetection(image_path)
  print("Detecting the objects in the given Video")
  print("This might take some time just sit back and relax")
  print("We will do the detection while you have your coffee")
  videoDection(video_path)

elif isImage:
  print("Detecting the objects in the given image")
  imageDetection(image_path)
elif isVideo:
  print("Detecting the objects in the given Video")
  print("This might take some time just sit back and relax")
  print("We will do the detection while you have your coffee")
  videoDection(video_path)
